language: groovy

script: ./gradlew -PbuildInfo.build.number=$TRAVIS_BUILD_NUMBER -PbuildInfo.buildUrl=https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_JOB_ID} -PbuildInfo.buildAgent.name=$USER -PbuildInfo.principal=$USER clean build publishToMavenLocal artifactoryPublish

jdk:
  - oraclejdk8

env:
  global:
  - TERM=dumb
  # bintray user
  - secure: "RyFV39ASbeBS3mTAP4ZCP09YlSHSP6yXNZA6BHsPsGFxCCQuxITxWQpxPo5WZrLMpzQkeFLLK5PIvqV717aoD/RnBxOyOiy4h9b2qzxATLmrPkZ+uUQstu1CdWJ8Qyirk92GAmnG8JmonuCaWDg3YCTPPmChfFNS84hV/7QI330="
  # bintray key
  - secure: "ARvYEbniOAyDuNpgE6PAaeuJAOvW9aFEKtsWxr9kjfs/8HDYxgR/ilZYnc/OIGVumHzBg4boRvPfSiCSAzOeHY0GwkhDvfA/G6bm9hXs+vFcYYUVDp8izLepHCrtA5cJUvHx61CIGzjVGZF2y8nk1aiSuIhKEQDvcsr7BzvGWoo="

notifications:
  email:
    - github@ihomeautomate.eu